### ISSUE TITLE
Incorrect formatting in examples/elfexe/hello64.asm and source/symbdump.inc

### ISSUE THREAD

**Issue by Sturwandan** [tgrysztar/fasm#1]
I have downloaded and unpacked fasm-1.73.27.tgz

While studying it, I have found out that ``hello64.asm`` is encoded in CP1252, which requires invoking iconv to read it.
Obviously, it's incorrect to use Windows encoding in file meant to be used in Linux.
Furthermore, the last line of the file is not terminated with '\n' (LF).
After finding one file like that, I have run search for more and found that ``source/symbdump.inc`` is also incorrectly formatted (last line is not terminated). I didn't find any other bad files, though.

**Comment by tgrysztar** [comment]
This assembler does not require the last line to be followed by any terminator (and furthermore, it allows various kinds of terminators, even mixed). Any port of fasm should be able to assemble such files correctly.

**Comment by Sturwandan** [comment]
@tgrysztar The problem is not that file doesn't assemble. The problem is that it's formatted incorrectly.

Like, imagine a program in C or Pascal, which has all statements in one line, separated by ``;``, such as:
```
bEgin wRitEln('Hey, there!'); wrItelN('I''m a valid pascal program!'); eNd.
```
The file would compile correctly, but it still would be incorrectly formatted source code, because the source code is supposed to have structural indentation, every line, including the last one, is supposed to be terminated with same terminator sequence, and most of statements should take a line of their own.

---

By the way, why does the tarball contain compiled binaries of examples?

**Comment by tgrysztar** [comment]
Not indenting the source in the usual way is not "incorrect", just non-standard (and you could consciously choose to do it for artistic or educational purposes).

As for the line breaks, my editors allow to add or omit the final one (it is something that can be distinguished and chosen while editing the file), following the conventions inherited from DOS Navigator. This is why some of these files happen to be this way, and I do not consider that an incorrect formatting.

**Comment by tgrysztar** [comment]
Please note that this is a repository of archival snapshots of the original source code. To report issues with actual releases, please use the official channel - the forums at https://board.flatassembler.net

**Comment by Sturwandan** [comment]
@tgrysztar 
1. just non-standard (and you could consciously choose to do it for artistic or educational purposes).
It might be OK for something like IOCCC nominant, but not for a program which you'd actually use.

2. This is why some of these files happen to be this way, and I do not consider that an incorrect formatting.
That's a common issue of multiple text editors. Text files with unterminated last line might be useful for some purposes, such as if they are meant to be directly inserted into binaries or something, however, in the case of a source code of a project, meant for production use, every line should be terminated correctly.

Editors like vim and nano would always terminate the last line, for example.

Unterminated lines are incorrect in Unix-like systems and cause inconvenience when they are output to the terminal with cat command. And obviously, the file in question is meant to be used in linux, given it's using linux syscalls.

Same goes to encoding other than UTF-8, because modern linux uses UTF-8 locales by default. Though since some systems with non-UTF-8 locales still exist, it's preferable to stick to ASCII character set, if possible.

Anyway, are you going to fix this particular issue, as in add the missing line terminators and convert the example file to ASCII or UTF-8?

**Comment by tgrysztar** [comment]
As mentioned above, if you'd like to discuss the changes to current fasm releases, please do it on the official forums.
